.github/workflows/pages.yml

Add workflow to deploy GitHub pages

Add GitHub pages workflow

---

src/app/carbon-estimator-form/carbon-estimator-form.component.html
src/app/carbon-estimator-form/carbon-estimator-form.constants.ts

Use 'digital services' instead of 'web presence'
Give more examples of the types of service we are talking about

Change wording around End-Users

---

docs/types.md
src/app/carbon-estimator-form/carbon-estimator-form.component.html
src/app/carbon-estimator-form/carbon-estimator-form.component.ts
src/app/carbon-estimator-form/carbon-estimator-form.constants.ts
src/app/estimation/estimate-downstream-emissions.spec.ts
src/app/estimation/estimate-downstream-emissions.ts
src/app/services/carbon-estimation.service.spec.ts
src/app/types/carbon-estimator.ts

Enforce minimum 1 Monthly Active User if downstream is included

Add an option to exclude downstream impacts

---

docs/estimation.md
docs/services.md
docs/types.md
src/app/carbon-estimator-form/carbon-estimator-form.component.html
src/app/carbon-estimator-form/carbon-estimator-form.component.ts
src/app/carbon-estimator-form/carbon-estimator-form.constants.ts
src/app/estimation/device-type.ts
src/app/estimation/device-usage.spec.ts
src/app/estimation/device-usage.ts
src/app/estimation/estimate-direct-emissions.spec.ts
src/app/estimation/estimate-direct-emissions.ts
src/app/estimation/estimate-upstream-emissions.spec.ts
src/app/estimation/estimate-upstream-emissions.ts
src/app/services/carbon-estimation.service.spec.ts
src/app/services/carbon-estimation.service.ts
src/app/types/carbon-estimator.ts

Refactored to allow for separation of network devices in the two areas.
Also updated the docs and removed some details where the diagrams were getting unreadable.

Add Employee location

---

package-lock.json
package.json
src/app/assumptions-and-limitation/assumptions-and-limitation.component.html
src/app/carbon-estimation/carbon-estimation.component.html
src/app/carbon-estimator-form/carbon-estimator-form.component.html
src/app/expansion-panel/expansion-panel.component.html
src/app/helper-info/helper-info.component.html
src/app/note/note.component.html
src/app/tech-carbon-estimator/tech-carbon-estimator.component.html
tailwind.config.js

- Scope tailwind pre-flight styles to tech-carbon-estimator 
- Scope tailwind classes to estimator component by prefixing with tce-

Scoping estimator styles

---

.gitignore
package-lock.json
src/app/carbon-estimation/carbon-estimation.constants.ts
src/app/expansion-panel/expansion-panel.component.html
tailwind.config.js

Fixed the issues with
- Popup styling: have to added popup container to pre-flight inclusion 
- Expand panel not hiding: add missing prefix to class
- Toolip icons not showing: add missing prefix to classes

Fixing missed scoped styles

---

src/app/assumptions-and-limitation/assumptions-and-limitation.component.html
src/app/services/carbon-estimation.service.spec.ts
src/app/services/carbon-estimation.service.ts

Also refactored the tests to remove manually added context around expected values.

Add Employee monitors to the carbon estimation

---

src/index.html
tailwind.config.js

Jira ticket: [SFD-101: Update published page to use same font as Scott Logic site](https://scottlogic.atlassian.net/browse/SFD-101)
Updates font to match [brand guidelines](https://scottlogic.atlassian.net/wiki/pages/viewpageattachments.action?pageId=4029579292&preview=%2F4029579292%2F4031152194%2FScott-Logic-Brand-Guidelines.pdf).

SFD-101: Update published page to use same font as Scott Logic site

---

README.md

[SFD-116 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-116)
Updates the documentation to say we're using Web Test Runner as our test runner.

SFD-116: Update docs to say we're using Web Test Runner rather than Karma.

---

docs/types.md
src/app/carbon-estimation/carbon-estimation.component.spec.ts
src/app/carbon-estimation/carbon-estimation.component.ts
src/app/estimation/device-usage.spec.ts
src/app/estimation/estimate-direct-emissions.spec.ts
src/app/estimation/estimate-direct-emissions.ts
src/app/estimation/estimate-upstream-emissions.spec.ts
src/app/estimation/estimate-upstream-emissions.ts
src/app/services/carbon-estimation.service.spec.ts
src/app/services/carbon-estimation.service.ts
src/app/tech-carbon-estimator/tech-carbon-estimator.component.spec.ts
src/app/types/carbon-estimator.ts

Covers user facing text and code so that it doesn't get confusing in future

Change 'User' to 'Employee'

---

src/app/carbon-estimator-form/carbon-estimator-form.component.html
src/app/carbon-estimator-form/carbon-estimator-form.component.spec.ts
src/app/carbon-estimator-form/carbon-estimator-form.component.ts
tailwind.config.js

[Jira ticket](https://scottlogic.atlassian.net/browse/SFD-96)
Adds an error message for the monthly active users input field.
Valid input:
Invalid input:

SFD-96: Update red invalid input box

---

src/app/carbon-estimation/carbon-estimation.component.ts

Jira ticket: [SFD-78](https://scottlogic.atlassian.net/jira/software/projects/SFD/boards/104?selectedIssue=SFD-78)
Adds debounce to chart resize.

SFD-78: Add debounce to chart resize

---

package-lock.json
package.json
scripts/publish.sh

This has already been used to publish to npm here: https://www.npmjs.com/package/@scottlogic/tech-carbon-estimator
In future it will probably be best to make these kind of changes include the version update only and have any other changes merged into main first.

Npm package

---

src/app/assumptions-and-limitation/assumptions-and-limitation.component.html

Detail new network device calculations and add some TCS glossary links.

Update assumptions text

---

src/app/carbon-estimator-form/carbon-estimator-form.component.spec.ts
src/app/carbon-estimator-form/carbon-estimator-form.component.ts
src/app/tech-carbon-estimator/tech-carbon-estimator.component.html
src/app/tech-carbon-estimator/tech-carbon-estimator.component.spec.ts
src/app/tech-carbon-estimator/tech-carbon-estimator.component.ts

Remove the estimation component if the form is reset

Remove the Diagram when 'Reset' button is clicked

---

src/app/carbon-estimator-form/carbon-estimator-form.component.html
src/app/carbon-estimator-form/carbon-estimator-form.component.ts

[SFD-97 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-97)
Makes the 'Calculate' button focusable when disabled.

SFD-97: Add accessibility to disabled 'Calculate' Button

---

package-lock.json
package.json
requirements.txt

- Override vulnerable node.js packages picked up by Dependabot
- Update vulnerable python package picked up by Dependabot

SFD-121 Investigate reported security vulnerability

---

package-lock.json
package.json

Updated version so that we can fully test dark mode in TCS

Publish version 0.0.2

---

.gitignore
playwright/README.md

[SFD-134 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-134)
Adds the .venv folder for Python virtual environments to the .gitignore file.

SFD-134: Add .venv to .gitignore

---

src/app/tech-carbon-estimator/tech-carbon-estimator.component.html
src/index.html

Remove padding from within tech-carbon-estimator component. Added it back via the index file.

SFD-145 Increase available space for SL hosted estimator

---

src/app/assumptions-and-limitation/assumptions-and-limitation.component.html

[SFD-144 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-144)
Fixes typos in the assumptions and limitations section.

SFD-144: Fix assumptions and limitations typos

---

src/app/carbon-estimation/carbon-estimation.component.spec.ts
src/app/carbon-estimation/carbon-estimation.component.ts
src/app/tech-carbon-estimator/tech-carbon-estimator.component.html

Increase the width when the component becomes side-by-side to 1024px, (lg in the [tailwind responsive design](https://tailwindcss.com/docs/responsive-design))

SFD-149 increase width when component becomes side-by-side

---

src/app/assumptions-and-limitation/assumptions-and-limitation.component.html

Add link to/from network embodied carbon note, with appropriate aria roles.

SFD-118 Improve accessibility of assumptions footnote

---

package-lock.json
package.json

Override `@web` sub-dependencies to remove `ip` dependency.

SFD-121: Fix security vulnerability

---

package-lock.json
package.json

Sets version to 0.1.0 for release.

Create release version 0.1.0

---

src/app/assumptions-and-limitation/assumptions-and-limitation.component.html
src/app/assumptions-and-limitation/assumptions-and-limitation.component.ts
src/app/carbon-estimation/carbon-estimation.component.html
src/app/carbon-estimation/carbon-estimation.component.ts
src/app/carbon-estimator-form/carbon-estimator-form.component.html
src/app/carbon-estimator-form/carbon-estimator-form.component.ts
src/app/directives/external-link.directive.spec.ts
src/app/directives/external-link.directive.ts
src/app/disclaimer/disclaimer.component.html
src/app/disclaimer/disclaimer.component.ts

- Added `ExternalLinkDirective` to reduce the amount of attributes we need to set.
- Apply directive to all external links.

SFD-173 External links replace the Estimator view

---

package-lock.json
package.json

Sets version to 0.2.0 for minor release.

Create release v0.2.0

---

.github/pull_request_template.md

[SFD-142 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-142)
Created template for pull requests to this repo.

SFD-142: Add PR Template

---

package-lock.json
package.json

Update version to 0.3.0

---

package-lock.json
package.json

Update package version to 0.3.1

Update version to 0.3.1

---

.github/workflows/buildAndTest.yml

Update build and test pipeline to include develop and release branches

Update buildAndTest.yml with develop and release branching

---

.github/actions/set-up-environment/action.yml
.github/workflows/publish-package.yml
.releaserc.yml
README.md
docs/publish_process.md
package-lock.json
package.json
scripts/prepare.sh
scripts/verify-release.sh

Resolves #171
- Updated Package Preparation so that it can be run locally
- Added `semantic-release` package and release configuration
- Updated Publish workflow to use semantic-release
- Updated Documentation around commit messages and publishing process
- Added verify-release script to error in case of no new version
Workflow run which was not allowed to publish from this branch: https://github.com/ScottLogic/sl-tech-carbon-estimator/actions/runs/16720707361/job/47324627236#step:5:8
Workflow run with branch temporarily added to list, plus verify-release script: https://github.com/ScottLogic/sl-tech-carbon-estimator/actions/runs/16727569296/job/47347195948

feat: Automate package versioning using semantic-release

---

.github/workflows/codeql.yml

- Adds CodeQL config for code scanning

#190 Create codeql.yml

---

src/app/assumptions-and-limitation/assumptions-and-limitation.component.spec.ts
src/app/assumptions-and-limitation/assumptions-and-limitation.component.ts
src/app/estimation/estimate-downstream-emissions.spec.ts
src/app/estimation/estimate-downstream-emissions.ts
src/app/services/carbon-estimation.service.ts
src/app/tech-carbon-estimator/tech-carbon-estimator.component.spec.ts

Resolves #&lt;Issue number&gt;
[&lt;Issue Code&gt; Jira ticket](https://scottlogic.atlassian.net/browse/Issue-Code)
Write a brief but concise description of the changes you have made.
Include any relevant screenshots of visual changes.

220 tech debt make downstream emissions calculation into a class
