README.md
Adds a comment about how to set ```core.autocrlf=input``` when cloning the repository. I found this resolved some issues I was having related to line endings when setting up the project in VSCode. (Files were still marked as CRLF in the editor when I applied the setting after cloning, the Prettier/VSCode line ending settings looked correct.)
=> Update line endings section of README

docs/components.md, docs/estimation.md, docs/services.md, docs/types.md, src/app/assumptions-and-limitation/assumptions-and-limitation.component.html, src/app/assumptions-and-limitation/assumptions-and-limitation.component.ts, src/app/carbon-estimator-form/carbon-estimator-form.component.ts, src/app/carbon-estimator-form/carbon-estimator-form.constants.ts, src/app/estimation/device-usage.spec.ts, src/app/estimation/device-usage.ts, src/app/estimation/estimate-downstream-emissions.spec.ts, src/app/estimation/estimate-downstream-emissions.ts, src/app/estimation/estimate-energy-emissions.spec.ts, src/app/estimation/estimate-energy-emissions.ts, src/app/estimation/estimate-indirect-emissions.spec.ts, src/app/estimation/estimate-indirect-emissions.ts, src/app/services/carbon-estimation.service.spec.ts, src/app/services/carbon-estimation.service.ts, src/app/services/carbon-intensity.service.spec.ts, src/app/services/carbon-intensity.service.ts, src/app/types/carbon-estimator.ts, src/app/types/units.ts
Also updated our WorldLocation to use the same format as CO2.js
Display the list in assumptions as grams instead of kilograms as it's easier to read and more commonly used form.
Updated some tests due to minor variations.
=> Use CO2.js for Carbon Intensity values

src/app/carbon-estimator-form/carbon-estimator-form.component.spec.ts, src/app/carbon-estimator-form/carbon-estimator-form.component.ts
I think this is the best way to achieve this, found the following blog covering some options: https://netbasal.com/three-ways-to-dynamically-alter-your-form-validation-in-angular-e5fd15f1e946
1. Dynamically Add a Control - This seems like it could cause problems converting to `EstimatorValues` in `handleSubmit()`.
2. Dynamically Add Validators - We don't create the `MinValidator` explicitly so we can't remove it (the `min` in the `<input>` creates one automatically).
3. Disable the Control - Basically gives us what we want and works no matter how many validators the control has.
I also noticed that it was happy to submit when the value was deleted completely, the `required` validator prevents this. And even though we don't use the `monthlyActiveUsers` value when `noDownstream` is set, I …
=> Ensure that form can always be submitted when opting out of end user calculations

angular.json, package.json, scripts/publish.sh
A prepare script will run when installing a dependency from a github repo url, so this will force npm to build the components when installing. The inclusion of a files property is necessary to include files in the package that would otherwise be excluded by the .gitignore file. It also excludes the unbuilt source and documentation that isn't needed but still includes the package.json and README. Also included favicon, which was missing from build until now.
This should allow us to add the estimator to TCS without relying on the npm registry or making a local link to the estimator. The latter option would not work with Github Actions. We may still publish to the npm registry so the publish script has been changed to remove the files entry, as it already moves all required files into a …
=> Add prepare script to allow estimator to be included via github url

.github/actions/set-up-environment/action.yml, .github/workflows/pages.yml, .github/workflows/pull-request.yml, README.md
Jira ticket: [https://scottlogic.atlassian.net/browse/SFD-89](https://scottlogic.atlassian.net/browse/SFD-89)
Adds a workflow that runs when a pull request is opened and when new commits are pushed to an open pull request. The workflow checks the app builds successfully and runs the unit tests.
=> SFD-89 Create merge pipeline

angular.json, package.json, scripts/publish.sh, src/app/assumptions-and-limitation/assumptions-and-limitation.component.html, src/app/carbon-estimator-form/carbon-estimator-form.component.html, src/app/note/note.component.html, src/app/tech-carbon-estimator/tech-carbon-estimator.component.html, src/sl-styles.css, src/styles.css
- Added additional configuration to build for npm package using original styling
- Use Primary/Secondary turquoise and Charcoal for production build
- Notes Component
- Input sliders
- Main buttons (with border-bottom and no radius)
**Notes**
**Sliders & Buttons**
**Buttons (on hover)**
Adding @jcamilleri-scottlogic and @dkrees for review in case @jantoun-scottlogic is still out tomorrow.
=> Custom styling for Scott Logic version of Estimator

src/sl-styles.css
Had to specify border width as a one off value as tailwind doesn't have 3 by default, p-0.5 = padding: 0.125rem, which is what the site uses.
=> Tweak button styling to match Scott Logic site

.github/workflows/pages.yml
[SFD-107 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-107)
Removes the merge trigger for the pages deployment workflow leaving only the manual trigger.
=> SFD-107: Change main pipeline to not publish from every commit

requirements.txt
Would like to get this in separately from the automation as I don't know how long that will take to get right.
=> Missed requirements.txt when adding xprocess

src/app/carbon-estimator-form/carbon-estimator-form.component.html
[SFD-126 Jira Ticket](https://scottlogic.atlassian.net/browse/SFD-126)
Fixes an issue where the error message for the monthly active users field would be broken up and formatted incorrectly on smaller screen sizes.
Issue:
After fix:
=> SFD-126: Inline error message for monthly active users field is formatted incorrectly on smaller screen sizes bugfix

src/app/carbon-estimation/carbon-estimation.component.spec.ts, src/app/carbon-estimation/carbon-estimation.component.ts
[SFD-124 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-124)
Caps the chart height based on screen height to prevent issues with the chart becoming stretched when the component is displayed in a tall iFrame.
In iFrame before fix:
In iFrame after fix:
I've capped based on screen height rather than aspect ratio for the time being, mostly due to the screen height cap seeming to work ok and being unfamiliar with using aspect ratio to set height and how it would work in various contexts. I think it looks ok on mobile views (checked with the Chrome device toggle) and laptop but we might need to revisit and use aspect ratio if we aren't getting the desired effect in some settings.
=> SFD-124: Limit the size/shape that the diagram can be

src/app/carbon-estimator-form/carbon-estimator-form.component.html
- Moved Reset before Calculate in html.
- Use `justify-content: flex-end` instead of `flex-direction: row-reverse` to give the same positioning.
=> SFD-110 Accessibility tab order

docs/components.md, src/app/disclaimer/disclaimer.component.html, src/app/disclaimer/disclaimer.component.spec.ts, src/app/disclaimer/disclaimer.component.ts, src/app/tech-carbon-estimator/tech-carbon-estimator.component.html, src/app/tech-carbon-estimator/tech-carbon-estimator.component.ts
Shown above form
Also remains above Assumptions when shown
Spent a bit of time trying to work out why I couldn't add padding to the disclaimer element but haven't managed to narrow it down, so have just added to the internal expansion panel instead.
=> SFD-120 Add a disclaimer around use of the tool

README.md, src/app/carbon-estimation/carbon-estimation.component.spec.ts, src/app/carbon-estimation/carbon-estimation.component.ts
[SFD-98 Jira ticket](https://scottlogic.atlassian.net/jira/software/projects/SFD/boards/104)
Scales the chart size with the browser zoom factor to fix a bug where the chart would become squashed when the browser zoom was increased.
Before fix:
After fix:
=> SFD-98: Chart scaling on zoom bugfix

.github/workflows/pages.yml, .github/workflows/publish-package.yml, .github/workflows/pull-request.yml, playwright/tests/test_0_TrialTest_HappyPath.py
Final process should be:
- Run tests
- Build package and upload as artifact
- Use artifact to publish to npm
- Use artifact and version tag to create release
It's not enforced but the intention is that you run the workflow manually using the corresponding tag/commit for the version.
Also updated the pages workflow so that it is triggered when a new release is created.
Tested as far as possible to ensure that npm publish is authenticated and draft release is created but need to run from main with an updated version for it to complete fully.
=> SFD-136 Set up workflow to publish npm package

src/app/tech-carbon-estimator/tech-carbon-estimator.component.html, src/package-index.html
- Added a footer to package-index.html for ease of testing
- Run with `ng serve --configuration npm-package` to use this version
- Removed dynamic viewport height to prevent parent being smaller than its children when zoomed in
=> SFD-141 Diagram can overlap TCS footer when zoomed in

playwright/tests/test_17_EstTool_UI_AssumpLimitations.py, src/app/assumptions-and-limitation/assumptions-and-limitation.component.html, src/app/assumptions-and-limitation/assumptions-and-limitation.component.spec.ts, src/app/assumptions-and-limitation/assumptions-and-limitation.component.ts, src/app/tech-carbon-estimator/tech-carbon-estimator.component.html, src/app/tech-carbon-estimator/tech-carbon-estimator.component.spec.ts, src/app/tech-carbon-estimator/tech-carbon-estimator.component.ts
[SFD-123 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-123)
Moves the button to open the assumptions and limitations view to the estimator form below the disclaimer section.
Notes:
- When closing the assumptions and limitations view, the open button is scrolled into view expect when pressing escape when the view does not have focus in which case the old behaviour was retained.
=> SFD-123: Add assumptions view option before calculation

src/app/carbon-estimator-form/carbon-estimator-form.component.html
[SFD-129 Jira Ticket](https://scottlogic.atlassian.net/browse/SFD-129)
Fixes broken aria labels.
Notes:
- The errors in the screenshots attached to the ticket were fixed in the [SFD-139 PR](https://github.com/ScottLogic/sl-tech-carbon-estimator/pull/98). There was one new error which was fixed in this ticket.
=> SFD-129: Fix broken aria labels

.github/actions/run-playwright/action.yml, requirements.txt
[SFD-115 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-115)
Adds artifact uploads in the playwright workflow for the traces and an HTML report file of the test results.
Notes:
WRT the unit tests, whilst Web Test Runner does support reporting, it seems that the experimental Angular builder which is the bridge between Angular and Web Test Runner doesn’t yet support this feature and there isn’t any documentation it so we may have to wait a bit to add reports for the unit tests.
On the Playwright front, I’ve added artifact uploads for the Playwright traces for failing tests and an HTML report using the pytest-html package which can be downloaded. @qgogay-scottlogic and @sdun-scottlogic are going to have a discussion about what sort of things we’d like to do with the test reporting …
=> SFD-115: Add reports for automated tests

src/app/carbon-estimation/carbon-estimation.component.html, src/app/expansion-panel/expansion-panel.component.html, src/index.html, src/package-index.html
- Add `<main>` landmarks to index pages - not strictly a problem as it depends where component used but makes it easier to test.
- Use `<figure>` element instead of a `<div>` as `role="presentation"` does not officially support labels.
- Remove `role="region"` from expansion panel as they should have a unique label.
Last one is the only possible controversial change, I'm not sure if there was a reason it originally had a region role?
=> SFD-122 Fix Axe accessibility issues

src/app/carbon-estimator-form/carbon-estimator-form.component.html, src/app/carbon-estimator-form/carbon-estimator-form.component.ts, src/package-styles.css, src/styles.css, tailwind.config.js
[SFD-143 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-143)
Changes the the error messages in dark mode to white text on a red background so they are easier to read.
=> SFD-143: Make dark mode error text easier to read

src/app/expansion-panel/expansion-panel.component.html
[SFD-167 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-167)
Fixes an issue where the buttons that expand and collapse the expansion panels don't work with the `enter` key.
Notes:
- This was caused by having both a `(click)` and a `(keydown.enter)` handler on the [button](https://github.com/ScottLogic/sl-tech-carbon-estimator/blob/main/src/app/expansion-panel/expansion-panel.component.html#L5-L6). (Previously this wasn’t a button HTML element and so both were required but now it’s a button element pressing enter fires the `(click)` event and the `(keydown.enter)` event is no longer needed.)
=> SFD-167: Expansion panel button bugfix

src/app/carbon-estimator-form/carbon-estimator-form.component.html, src/app/carbon-estimator-form/carbon-estimator-form.component.ts, src/app/carbon-estimator-form/carbon-estimator-form.constants.ts, src/app/error-summary/error-summary.component.html, src/app/error-summary/error-summary.component.spec.ts, src/app/error-summary/error-summary.component.ts, src/app/tech-carbon-estimator/tech-carbon-estimator.component.html, src/package-styles.css, src/styles.css
[SFD-128 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-128)
Adds an error summary to display form validation errors. Includes links to the invalid input fields.
Notes:
-   The 'calculate' button was previously disabled when there were validation errors. It has been enabled at all times but the error summary will be shown if there are validation errors. This is so that the error feedback is the same whether the form is submitted using the 'enter' key or the 'calculate' button. 
Error summary:
Error summary dark mode:
=> SFD-128: Add error summary for validation errors

src/app/carbon-estimator-form/carbon-estimator-form.component.ts
[SFD-196 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-196)
Fixes a bug where the error summary is still shown after the form is reset.
=> SFD-196: Error summary persisting on form reset bugfix

src/app/carbon-estimator-form/carbon-estimator-form.component.html, src/app/carbon-estimator-form/carbon-estimator-form.component.spec.ts, src/app/carbon-estimator-form/carbon-estimator-form.component.ts, src/app/carbon-estimator-form/carbon-estimator-form.constants.ts, src/app/services/form-state.service.spec.ts, src/app/services/form-state.service.ts, src/app/services/storage.service.spec.ts, src/app/services/storage.service.ts, src/app/utils/cost-range.spec.ts, src/app/utils/cost-range.ts
[SFD-171 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-171)
Persists the form state in session storage when swapping away from the form view or navigating away from the page.
=> SFD-171: Persist form state

playwright/tests/test_17_EstTool_UI_AssumpLimitations.py, src/app/assumptions-and-limitation/assumptions-and-limitation.component.html, src/app/assumptions-and-limitation/assumptions-and-limitation.component.spec.ts, src/app/assumptions-and-limitation/assumptions-and-limitation.component.ts, src/app/tab/tabs/tabs.component.html, src/app/tech-carbon-estimator/tech-carbon-estimator.component.html, src/app/tech-carbon-estimator/tech-carbon-estimator.component.spec.ts, src/app/tech-carbon-estimator/tech-carbon-estimator.component.ts
- Added tabs component with items for form and assumptions
- Removed 'close' buttons and escape key functionality.
=> SFD-175 Tab to switch between form and assumptions view

src/app/carbon-estimation-treemap/carbon-estimation-treemap.component.html, src/app/carbon-estimation-treemap/carbon-estimation-treemap.component.ts, src/app/carbon-estimation/carbon-estimation.component.ts
[SFD-194 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-194)
Ensure internal apex chart is ready before attempting to update its options.
There is a short period of time where the ng-apexchart `ChartComponent` has been created but it hasn't finished setting up the ApexChart element it's wrapping. Potentially a bug in their code but the `chartReady` event suggests it's something to be expected.
=> SFD-194: Fix error on app startup

.github/workflows/pages.yml, .github/workflows/publish-package.yml, .github/workflows/shared-pages.yml
[SFD-193 Jira ticket](https://scottlogic.atlassian.net/browse/SFD-193)
Add a shared workflow to publish pages, which can only be called from other workflows. There are now 3 workflows that can be triggered manually:
- **Build and Test** (`buildAndTest.yml`)
- **Deploy estimator pages** (`pages.yml`)
- **Publish new package** (`publish-package.yml`)
And one that can only be called from others:
- **Shared Pages publish workflow** (`shared-pages.yml`)
**Deploy estimator pages** is now a simple workflow that only calls other workflows, `buildAndTest` followed by `shared-pages`.  In theory we should not need to use this in future but we will keep it for now. **Publish new package** has only changed to call `shared-pages`.
=> SFD-193: Avoid duplication of build and test steps in publish pipeline

src/app/carbon-estimator-form/carbon-estimator-form.constants.ts
Issue #180
- Specified text colour for question expansion panels when in dark mode
(Page looks different due to tailwind issues that need to be resolved. Have confirmed that without this change, the text is still shown as white in latest develop)
=> fix: Colour contrast for expansion panels is not suitable ratio in darkmode

.github/workflows/publish-package.yml
Potential fix for [https://github.com/ScottLogic/sl-tech-carbon-estimator/security/code-scanning/5](https://github.com/ScottLogic/sl-tech-carbon-estimator/security/code-scanning/5)
To fix the problem, add a `permissions` block to the `test` job in `.github/workflows/publish-package.yml`. This block should specify the minimal permissions required for the job. Since the job is named `test` and likely only runs tests (as implied by its name and the fact that it uses a build-and-test workflow), it probably only needs read access to the repository contents. Therefore, set `permissions: contents: read` for the `test` job. This change should be made directly under the `test:` job definition, at the same indentation level as `uses:`.
---
_Suggested fixes powered by Copilot Autofix. Review …
=> Potential fix for code scanning alert no. 5: Workflow does not contain permissions

src/app/carbon-estimation-table/carbon-estimation-table.component.spec.ts, src/app/carbon-estimation-treemap/carbon-estimation-treemap.component.spec.ts, src/app/carbon-estimation/carbon-estimation.component.spec.ts, src/app/estimation/estimate-downstream-emissions.spec.ts, src/app/estimation/estimate-downstream-emissions.ts, src/app/tech-carbon-estimator/tech-carbon-estimator.component.spec.ts, src/app/types/carbon-estimator.ts
- Adds a new `downstreamInfrastructure` to the `downstreamEmissions` type to match schema v0.0.2
- Updates tests to default the property value
- Adds function stub for later updates when calculation method available
=> #145 Create Downstream Infrastructure emissions type for schema v0.0.2

src/app/carbon-estimator-form/carbon-estimator-form.component.html, src/styles.css
- Added custom styles `tce-select` and `tce-input` which provide a consistent look to inputs in light or dark mode.
- `tce-select > option` correctly styles option values for dark mode
=> #198 Bugfix for dropdown contrast in dark mode
